FROM php:7.4-apache

# Define o diretório de trabalho
WORKDIR /var/www/html

# Copia os arquivos de configuração do Apache
COPY ./default.web.conf /etc/apache2/sites-available/000-default.conf

# Copia o arquivo de configuração do PHP
COPY ./php.ini /usr/local/etc/php/

# Copia os certificados SSL
COPY ./ssl.crt /etc/apache2/ssl/
COPY ./ssl.key /etc/apache2/ssl/

# Instala as dependências necessárias
RUN apt-get update && apt-get install -y \
        libpng-dev \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libonig-dev \
        zip \
        curl \
        unzip \
        libc-client-dev \
        libkrb5-dev \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install zip \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap \
    && rm -r /var/lib/apt/lists/*

# Configura as permissões do diretório de trabalho
RUN chown -R www-data:www-data /var/www/html

# Habilita os módulos necessários do Apache
RUN a2enmod rewrite \
    && a2enmod ssl

# Expose as portas utilizadas
EXPOSE 80
EXPOSE 443

# Inicia o servidor Apache
CMD ["apache2-foreground"]
